apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: mmowbray
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/mmowbrayharborproject/db@sha256:3ee098e0ae70841f67b9a0c7964e971d7273e92b541a4041e834c4a38424b891
        ports:
        - containerPort: 5432
